import {
  TbBrandTypescript,
  TbBrandReact,
  TbBrandCss3,
  TbBrandReactNative,
  TbApi,
  TbBrandVite,
  TbBrandFramerMotion,
} from "react-icons/tb";
import {
  SiRedux,
  SiNextdotjs,
  SiJest,
  SiGraphql,
  SiTestinglibrary,
  SiPostcss,
  SiMui,
  SiMaterialdesign,
  SiPostgresql,
  SiMysql,
  SiMongodb,
  SiRedis,
  SiNginx,
  SiDocker,
  SiGithubactions,
  SiGnubash,
  SiNpm,
  SiReactbootstrap,
  SiMedusa,
  SiMantine,
  SiTailwindcss,
  SiJsonwebtokens,
  SiExpress,
  SiTurborepo,
} from "react-icons/si";
import { FaNodeJs } from "react-icons/fa";
import { FaBootstrap, FaSass, FaShopify, FaYarn } from "react-icons/fa6";

export const iconMap: Record<string, React.ReactElement> = {
  ///Frontend
  FaShopify: <FaShopify />,
  SiMedusa: <SiMedusa />,
  TbApi: <TbApi />,
  TbBrandVite: <TbBrandVite />,
  SiReactbootstrap: <SiReactbootstrap />,
  TbBrandTypescript: <TbBrandTypescript />,
  TbBrandReact: <TbBrandReact />,
  SiRedux: <SiRedux />,
  SiNextdotjs: <SiNextdotjs />,
  SiJest: <SiJest />,
  SiGraphql: <SiGraphql />,
  TbBrandReactNative: <TbBrandReactNative />,
  SiTestinglibrary: <SiTestinglibrary />,
  ///Styles
  TbBrandCss3: <TbBrandCss3 />,
  SiPostcss: <SiPostcss />,
  SiMui: <SiMui />,
  SiMaterialdesign: <SiMaterialdesign />,
  SiMantine: <SiMantine />,
  FaBootstrap: <FaBootstrap />,
  SiTailwindcss: <SiTailwindcss />,
  FaSass: <FaSass />,
  TbBrandFramer: <TbBrandFramerMotion />,

  ////Backend
  SiPostgresql: <SiPostgresql />,
  SiMysql: <SiMysql />,
  SiMongodb: <SiMongodb />,
  SiRedis: <SiRedis />,
  FaNodeJs: <FaNodeJs />,
  SiJsonwebtokens: <SiJsonwebtokens />,
  SiRest: <TbApi />,
  SiExpress: <SiExpress />,
  ////DevOps
  SiTurborepo: <SiTurborepo />,
  SiNginx: <SiNginx />,
  SiDocker: <SiDocker />,
  SiGithubactions: <SiGithubactions />,
  SiGnubash: <SiGnubash />,
  SiNpm: <SiNpm />,
  FaYarn: <FaYarn />,
};
